# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.2

pipelines:
 default:
  - step:
     name: AWS Instance make
     script:
       - pipe: atlassian/ssh-run:0.1.1
         variables:
           SSH_USER: 'ubuntu'
           SERVER: 'ec2-18-218-53-189.us-east-2.compute.amazonaws.com'
           MODE: 'command'
           COMMAND: 'bash serverStartup.sh'
   